curl -o beans-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=BEANS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=DRY%20EDIBLE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o beans-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=BEANS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=DRY%20EDIBLE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o beans-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=BEANS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=DRY%20EDIBLE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &

curl -o cotton-pima-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=PIMA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &
curl -o cotton-pima-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=PIMA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &
curl -o cotton-pima-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=PIMA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &

curl -o cotton-upland-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=UPLAND&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &
curl -o cotton-upland-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=UPLAND&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &
curl -o cotton-upland-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=COTTON&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=UPLAND&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=480%20LB%20BALES" &



curl -o soybeans-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o soybeans-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o soybeans-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o soybeans-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o soybeans-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o soybeans-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o soybeans-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o soybeans-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o soybeans-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o soybeans-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o soybeans-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o soybeans-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SOYBEANS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o sugarbeets-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarbeets-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarbeets-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sugarbeets-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarbeets-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarbeets-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sugarbeets-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o sugarbeets-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o sugarbeets-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &

curl -o sugarbeets-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o sugarbeets-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o sugarbeets-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARBEETS&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &

curl -o sunflower-oil-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sunflower-oil-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sunflower-oil-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sunflower-oil-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sunflower-oil-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sunflower-oil-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sunflower-oil-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o sunflower-oil-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o sunflower-oil-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &

curl -o sunflower-oil-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o sunflower-oil-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o sunflower-oil-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &

curl -o "sunflower-non-oil-planted-county.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o "sunflower-non-oil-planted-state.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o "sunflower-non-oil-planted-national.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o "sunflower-non-oil-harvested-county.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o "sunflower-non-oil-harvested-state.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o "sunflower-non-oil-harvested-national.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o "sunflower-non-oil-production-county.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o "sunflower-non-oil-production-state.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o "sunflower-non-oil-production-national.json" "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &

curl -o sunflower-non-oil-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o sunflower-non-oil-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o sunflower-non-oil-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUNFLOWER&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=NON-OIL%20TYPE&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &

curl -o sweet-potatoes-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sweet-potatoes-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sweet-potatoes-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sweet-potatoes-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sweet-potatoes-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sweet-potatoes-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sweet-potatoes-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT" &
curl -o sweet-potatoes-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT" &
curl -o sweet-potatoes-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT" &

curl -o sweet-potatoes-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT%20/%20ACRE" &
curl -o sweet-potatoes-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT%20/%20ACRE" &
curl -o sweet-potatoes-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SWEET%20POTATOES&group_desc=VEGETABLES&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=CWT%20/%20ACRE" &

curl -o tobacco-burley-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o tobacco-burley-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o tobacco-burley-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o tobacco-burley-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o tobacco-burley-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o tobacco-burley-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &

curl -o tobacco-burley-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o tobacco-burley-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o tobacco-burley-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=AIR-CURED%20LIGHT%20BURLEY%20(TYPE%2031)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &

curl -o tobacco-flue-cured-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o tobacco-flue-cured-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o tobacco-flue-cured-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o tobacco-flue-cured-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o tobacco-flue-cured-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &
curl -o tobacco-flue-cured-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB" &

curl -o tobacco-flue-cured-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o tobacco-flue-cured-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &
curl -o tobacco-flue-cured-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=TOBACCO&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=FLUE-CURED%20(CLASS%201)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=LB%20/%20ACRE" &

curl -o wheat-durum-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-durum-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-durum-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-durum-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-durum-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-durum-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-durum-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-durum-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-durum-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o wheat-durum-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-durum-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-durum-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20DURUM&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o wheat-spring-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-spring-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-spring-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-spring-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-spring-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-spring-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-spring-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-spring-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-spring-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o wheat-spring-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-spring-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-spring-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=SPRING,%20(EXCL%20DURUM)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o wheat-winter-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-winter-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-winter-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-winter-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-winter-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o wheat-winter-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o wheat-winter-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-winter-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o wheat-winter-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o wheat-winter-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-winter-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o wheat-winter-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=WHEAT&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=WINTER&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o hay-alfalfa-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o hay-alfalfa-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o hay-alfalfa-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o hay-alfalfa-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o hay-alfalfa-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o hay-alfalfa-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &

curl -o hay-alfalfa-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o hay-alfalfa-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o hay-alfalfa-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALFALFA&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &

curl -o hay-others-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o hay-others-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o hay-others-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o hay-others-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o hay-others-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o hay-others-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &

curl -o hay-others-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o hay-others-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o hay-others-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=HAY&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=(EXCL%20ALFALFA)&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &

curl -o corn-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o corn-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o corn-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o corn-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o corn-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o corn-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o corn-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o corn-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o corn-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o corn-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o corn-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o corn-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=CORN&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o sorghum-planted-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sorghum-planted-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sorghum-planted-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20PLANTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=ALL%20UTILIZATION%20PRACTICES&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sorghum-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sorghum-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sorghum-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sorghum-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o sorghum-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &
curl -o sorghum-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU" &

curl -o sorghum-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o sorghum-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &
curl -o sorghum-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SORGHUM&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=GRAIN&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=BU%20/%20ACRE" &

curl -o sugarcane-harvested-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarcane-harvested-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &
curl -o sugarcane-harvested-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=AREA%20HARVESTED&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=ACRES" &

curl -o sugarcane-production-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o sugarcane-production-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &
curl -o sugarcane-production-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=PRODUCTION&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS" &

curl -o sugarcane-yield-county.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=COUNTY&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o sugarcane-yield-state.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=STATE&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &
curl -o sugarcane-yield-national.json "http://nass-api.azurewebsites.net/api/api_get?commodity_desc=SUGARCANE&group_desc=FIELD%20CROPS&agg_level_desc=NATIONAL&statisticcat_desc=YIELD&source_desc=SURVEY&freq_desc=ANNUAL&prodn_practice_desc=ALL%20PRODUCTION%20PRACTICES&util_practice_desc=SUGAR&class_desc=ALL%20CLASSES&domain_desc=TOTAL&reference_period_desc=YEAR&value__ne=(D)&unit_desc=TONS%20/%20ACRE" &

